// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBzO8F0VMBWLtZKkiG2qsv3YfayepSe1E',
    appId: '1:561742967246:web:1d72fd53b101a68b23bb9f',
    messagingSenderId: '561742967246',
    projectId: 'iti---final-flutter-project',
    authDomain: 'iti---final-flutter-project.firebaseapp.com',
    storageBucket: 'iti---final-flutter-project.firebasestorage.app',
    measurementId: 'G-XWN9P09ZS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1xyOzvrKgQQA4JHiYvxoCAF13LjgZllE',
    appId: '1:561742967246:android:6861378f447952b523bb9f',
    messagingSenderId: '561742967246',
    projectId: 'iti---final-flutter-project',
    storageBucket: 'iti---final-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMB1ihURbrhvvUBMU1zsMBwD7WvMYg9g4',
    appId: '1:561742967246:ios:e1e46efdf38f770023bb9f',
    messagingSenderId: '561742967246',
    projectId: 'iti---final-flutter-project',
    storageBucket: 'iti---final-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.finalFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMB1ihURbrhvvUBMU1zsMBwD7WvMYg9g4',
    appId: '1:561742967246:ios:e1e46efdf38f770023bb9f',
    messagingSenderId: '561742967246',
    projectId: 'iti---final-flutter-project',
    storageBucket: 'iti---final-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.finalFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBzO8F0VMBWLtZKkiG2qsv3YfayepSe1E',
    appId: '1:561742967246:web:13c1177c3ca437ea23bb9f',
    messagingSenderId: '561742967246',
    projectId: 'iti---final-flutter-project',
    authDomain: 'iti---final-flutter-project.firebaseapp.com',
    storageBucket: 'iti---final-flutter-project.firebasestorage.app',
    measurementId: 'G-F73YYX802T',
  );
}
